<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Santri extends Model
{
    use HasFactory;

    protected $fillable = [
        'nama_santri',
        'jenis_kelamin',
        'tempat_lahir_santri',
        'tanggal_lahir_santri',
        'jumlah_saudara',
        'anak_ke',
        'universitas',
        'pendidikan',
        'fakultas',
        'gelar_saat_lulus',
        'tahun_masuk_ppm',
        'kabupaten',
        'status_rumah',
        'golongan_darah',
        'riwayat_penyakit',
        'no_hp_santri',
        'email_santri',
        'alamat_santri',
        'kode_pos',
        'nama_ayah',
        'tempat_lahir_ayah',
        'tanggal_lahir_ayah',
        'status_ayah',
        'pendidikan_ayah',
        'pekerjaan_ayah',
        'penghasilan_ayah',
        'no_hp_ayah',
        'nama_ibu',
        'status_ibu',
        'tempat_lahir_ibu',
        'tanggal_lahir_ibu',
        'no_hp_ibu',
        'pendidikan_ibu',
        'pekerjaan_ibu',
        'penghasilan_ibu',
        'alamat_orang_tua',
        'asal_kelompok_sambung',
        'asal_desa_sambung',
        'asal_daerah_sambung',
        'jumlah_hafalan',
        'status_mubaligh',
        'keahlian',
        'prestasi',
        'bahasa_asing',
        'facebook',
        'instagram',
        'nama_wali',
        'tempat_lahir_wali',
        'tanggal_lahir_wali',
        'pekerjaan_wali',
        'alamat_wali',
        'no_hp_wali',
        'nama_imam_kelompok',
        'no_hp_imam',
        'asal_kelompok_imam',
        'alamat_imam',
        'kartu_keluarga',
        'ktp',
        'pas_foto',
        'surat_sambung',
        'kartu_keluarga',
        'ktp',
        'pas_foto',
        'surat_sambung',
    ];
}
